basePath: /v1
definitions:
  models.Session:
    properties:
      $createdAt:
        type: string
      $id:
        type: string
      $updatedAt:
        type: string
      clientCode:
        type: string
      clientEngine:
        type: string
      clientEngineVersion:
        type: string
      clientName:
        type: string
      clientType:
        type: string
      clientVersion:
        type: string
      countryCode:
        type: string
      countryName:
        type: string
      current:
        type: boolean
      deviceBrand:
        type: string
      deviceModel:
        type: string
      deviceName:
        type: string
      expire:
        type: string
      factors:
        items:
          type: string
        type: array
      ip:
        type: string
      mfaUpdatedAt:
        type: string
      osCode:
        type: string
      osName:
        type: string
      osVersion:
        type: string
      provider:
        type: string
      providerAccessToken:
        type: string
      providerAccessTokenExpiry:
        type: string
      providerRefreshToken:
        type: string
      providerUid:
        type: string
      secret:
        type: string
      userId:
        type: string
    type: object
info:
  contact: {}
  description: API documentation for Kaho BaaS
  title: Kaho BaaS API Documentation
  version: "1.0"
paths:
  /account/sessions/login:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Authenticate user credentials and start a user session.
      parameters:
      - description: Project ID
        in: header
        name: X-Kaho-Project
        required: true
        type: string
      - description: User Email
        in: formData
        name: email
        required: true
        type: string
      - description: User Password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Login success response
          schema:
            type: string
        "400":
          description: X-Kaho-Project is required
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Invalid credentials
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Server error
          schema:
            additionalProperties: true
            type: object
      summary: Login user for a project
      tags:
      - account
  /account/sessions/register:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Authenticate user credentials and start a user session.
      parameters:
      - description: Project ID
        in: header
        name: X-Kaho-Project
        required: true
        type: string
      - description: User Email
        in: formData
        name: email
        required: true
        type: string
      - description: User Password
        in: formData
        name: password
        required: true
        type: string
      - description: User Name
        in: formData
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Login success response
          schema:
            type: string
        "201":
          description: Login success response
          schema:
            $ref: '#/definitions/models.Session'
        "400":
          description: X-Kaho-Project is required
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Invalid credentials
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Server error
          schema:
            additionalProperties: true
            type: object
      summary: Register user for a project
      tags:
      - account
swagger: "2.0"
